[package]

name = "geo"
description = "Geo generics/utils"
version = "0.0.7"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/rust-geo"
documentation = "https://georust.github.io/rust-geo/"
